package com.humaltelu.drinkinggame.model;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName="packs")
public class Pack {

    @DynamoDBHashKey
    @DynamoDBAttribute
    private String user_id;
    @DynamoDBRangeKey
    @DynamoDBAutoGeneratedKey
    private String pack_id;
    @DynamoDBAttribute
    private Integer private_tier;
    @DynamoDBAttribute
    private String share_code;
    @DynamoDBAttribute
    private String pack_name;
    @DynamoDBAttribute
    private Integer day_stamp;
    @DynamoDBAttribute
    private Integer likes;
    @DynamoDBAttribute
    private Integer report_count;
    @DynamoDBAttribute
    private List <Task> tasks;
    
}
